config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord

  validates :name, :address, :description, :price_per_night, :number_of_guests, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController

  def index
    @flats = Flat.all
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flats_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def edit
    @flat = Flat.find(params[:id])
  end

  def update
    @flat = Flat.find(params[:id])
    @flat.update(flat_params)
  end

  def destroy
    @flat = Flat.find(params[:id])
    @flat.destroy
    redirect_to flats_path, status: :see_other
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/edit.html.erb
<div class="container">
  <h1>Edit flat</h1>

  <%= simple_form_for(@flat) do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :price_per_night %>
    <%= f.input :number_of_guests %>
    <%= f.submit %>
  <% end %>
</div>

app/views/flats/index.html.erb
<div class="container">
  <h1>All your flats</h1>
  <h2><%= @flats.count %> flats</h3>
  <h3><%= link_to "Create a flat", new_flat_path, class: "btn btn-ghost" %></h3>

  <div class="cards">
    <% @flats.each do |flat|%>
      <div class="card shadow-sm" style="width: 24rem;">
        <img src="https://cdn.apartmenttherapy.info/image/upload/f_auto,q_auto:eco,c_fit,w_730,h_487/at%2Fhouse%20tours%2F2021-04%2FErin%20K%2FKERR-130-CLARKSON-2R-01-020577-EDIT-WEB" class="img-fluid" alt="...">
        <div class="card-body">
          <h2 class="card-title"><%= flat.description%> </h2>
          <p class="card-text" id="flat-address"><%= flat.address %></p>
          <div class="d-flex align-items-center">
          <p class="card-text p-0"><%= flat.price_per_night %></p>
            <i class="fa-solid fa-euro-sign"></i>
          </div>
          <div class="d-flex align-items-center">
            <p class="card-text"><%= flat.number_of_guests %></p>
            <i class="fa-solid fa-users"></i>
          </div>
        </div>
        <div class="d-flex justify-content-between border-top" id="more">
          <p class="m-0 p-3" id="button-more"><%= link_to 'More info', flat_path(flat) %></p>
          <p class="m-0 p-3" id="button-edit"><%= link_to 'Update flat', edit_flat_path(flat) %></p>
          <p class="m-0 p-3" id="button-delete"><%= link_to "Delete", flat_path(flat), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %> </p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<div class="container">
  <h1>Create new flat</h1>

  <%= simple_form_for(@flat) do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :price_per_night %>
    <%= f.input :number_of_guests %>
    <%= f.submit %>
  <% end %>
</div>

app/views/flats/show.html.erb
<div class="banner position-relative" style="background-image: url(https://www.thestatesman.com/wp-content/uploads/2020/04/googl_ED.jpg);">
  <div class="container">
    <div class="flat-card position-absolute top-100 start-50 translate-middle" id="flat-informations">
      <h1><%= @flat.description %></h1>
      <h4><%= @flat.address %></h4>
    </div>

  </div>
</div>
<div id="empty-box"></div>
<div class="container mt-5">
  <h2>Details</h2>
  <div class="d-flex align-items-center">
    <p class="card-text p-0"><%= @flat.price_per_night %></p>
    <i class="fa-solid fa-euro-sign"></i>
  </div>
  <div class="d-flex align-items-center">
    <p class="card-text"><%= @flat.number_of_guests %></p>
    <i class="fa-solid fa-users"></i>
  </div>
    <p class="card-text"><%= @flat.name %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <%# BOOTSTRAP %>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    >
    <%# FONTAWESOME %>
    <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v6.1.2/css/all.css"
    >
  </head>

  <body>
    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon sticky-top">
      <div class="container-fluid">
        <%= link_to "#", class: "navbar-brand" do %>
        <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
        <% end %>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto">
            <li class="nav-item active">
              <%= link_to "Home", "/flats", class: "nav-link" %>
            </li>
            <li class="nav-item dropdown">
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <%= link_to "Action", "#", class: "dropdown-item" %>
                <%= link_to "Another action", "#", class: "dropdown-item" %>
                <%= link_to "Log out", "#", class: "dropdown-item", data: {turbo_method: :delete} %>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <%= yield %>
  </body>
</html>